[build]
  # No build command needed for static site
  command = ""
  # Publish directory
  publish = "."
  
[build.environment]
  # Environment variables
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; media-src 'self'; object-src 'none'"

# Cache static assets
[[headers]]
  for = "/src/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# PWA files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0"

# Redirects are handled by _redirects file
# Force HTTPS
[[redirects]]
  from = "http://planbconstructioninc.netlify.app/*"
  to = "https://planbconstructioninc.netlify.app/:splat"
  status = 301
  force = true

# Remove trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 200

# Functions directory (for future use)
[functions]
  directory = "netlify/functions"

# Form handling
[forms]
  settings = { "spam_protection" = "honeypot" }

# Branch deploy contexts
[context.production]
  command = ""
  publish = "."

[context.deploy-preview]
  command = ""
  publish = "."

[context.branch-deploy]
  command = ""
  publish = "."

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://planbconstructioninc.com"
    
[[plugins]]
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = ["production"] 